modules_dir = "artifacts/"

[[module]]
    name = "sqlite3"

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }

[[module]]
name = "academy_backend"
logger_enabled = true